// <auto-generated />
using System;
using DiplomeProject.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomeProject.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20230611155531_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomeProject.DB.IdentityModels.DbUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiplomeProject.DB.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "category1",
                            Name = "Засоби для прання"
                        },
                        new
                        {
                            Id = "category2",
                            Name = "Порошки для миття посуду"
                        },
                        new
                        {
                            Id = "category3",
                            Name = "Засоби для прибирання"
                        },
                        new
                        {
                            Id = "category4",
                            Name = "Засоби для кухні"
                        });
                });

            modelBuilder.Entity("DiplomeProject.DB.Models.Producer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = "ariel01",
                            Country = "Germany",
                            Name = "Ariel",
                            Rating = 5
                        },
                        new
                        {
                            Id = "W502",
                            Country = "Germany",
                            Name = "W5",
                            Rating = 5
                        },
                        new
                        {
                            Id = "Bonus03",
                            Country = "France",
                            Name = "Bonus",
                            Rating = 5
                        },
                        new
                        {
                            Id = "Domestos04",
                            Country = "United Kingdom",
                            Name = "Domestos",
                            Rating = 5
                        },
                        new
                        {
                            Id = "Denkmit05",
                            Country = "Czech",
                            Name = "Denkmit",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("DiplomeProject.DB.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DiscountPercent")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProducerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("WeightInKilogram")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "82f29bb2-de09-4102-8b5e-207ab65ea22b",
                            Article = "HP344410",
                            CategoryId = "category2",
                            Description = "Унікальні капсули для прання кольорових речей Ariel Professional color від торгової марки Ariel подарують вашим речам неперевершену чистоту! Завдяки вмісту активних компонентів засіб чудово справляється навіть зі складними плямами на одязі, зберігаючи при цьому початкову насиченість кольору.\r\n\r\nКапсули для прання Ariel Professional color мають унікальну багатокамерну структуру, що означає, що інгредієнти відокремлені один від одного та не з'єднуються один з одним до початку прання, завдяки чому забезпечують надзвичайно концентровану пральну здатність. Інноваційне покриття капсул для прання Ariel повністю розчиняється при контакті з водою, вивільняючи спеціальні формули, що дозволяють видаляти різні види плям.\r\n\r\nКапсули Ariel – найкращий засіб у рідкій формі, що містить необхідну кількість окремих інгредієнтів. Цей засіб є у 3 рази більш концентрованим у порівнянні з іншими пральними засобами. Його перевагою є відсутність у складі фосфатів, що робить використання капсул абсолютно безпечним. Після прання ваші речі пахнуть свіжістю.",
                            DiscountPercent = 17f,
                            Name = "Капсули для прання Ariel Professional color 80 шт",
                            PhotoPath = "/product1",
                            Price = 1273f,
                            ProducerId = "ariel01",
                            StatusId = "avaliable",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "1d791781-812d-4f57-a42a-af35436ac137",
                            Article = "HP344397",
                            CategoryId = "category2",
                            Description = "Унікальні капсули для прання кольорових речей Ariel Professional original від торгової марки Ariel подарують вашим речам неперевершену чистоту! Завдяки вмісту активних компонентів засіб чудово справляється навіть зі складними плямами на одязі, зберігаючи при цьому початкову насиченість кольору.\r\n\r\nКапсули для прання Ariel Professional original мають унікальну багатокамерну структуру, що означає, що інгредієнти відокремлені один від одного та не з'єднуються один з одним до початку прання, завдяки чому забезпечують надзвичайно концентровану пральну здатність. Інноваційне покриття капсул для прання Ariel повністю розчиняється при контакті з водою, вивільняючи спеціальні формули, що дозволяють видаляти різні види плям.\r\n\r\nКапсули Ariel – найкращий засіб у рідкій формі, що містить необхідну кількість окремих інгредієнтів. Цей засіб є у 3 рази більш концентрованим у порівнянні з іншими пральними засобами. Його перевагою є відсутність у складі фосфатів, що робить використання капсул абсолютно безпечним. Після прання ваші речі пахнуть свіжістю.",
                            DiscountPercent = 0f,
                            Name = "Капсули для прання Ariel Professional original 80 шт",
                            PhotoPath = "/product2",
                            Price = 1282f,
                            ProducerId = "ariel01",
                            StatusId = "runOut",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "fc7be537-04d5-45e6-afa1-e4e99662a079",
                            Article = "HP821748",
                            CategoryId = "category1",
                            Description = "Універсальний плямовивідник-спрей Ariel Diamond Bright розроблений для видалення плям на кольорових, світлих і білих речах.\r\n\r\nЗасіб з технологією Oxifoam - активної кисневої піни - досягає помітного результату вже після першої обробки і прання. Рідина на основі унікальних інгредієнтів, усуває навіть найстійкіші жирові та інші плями від їжі і напоїв. Ariel Diamond Bright чудово впорається як зі свіжими, так і застарілими плямами.\r\n\r\nПлямовивідник Ariel не шкодить тканині, доглядаючи за волокнами під час прання. Завдяки інноваційній формулі всі кольори залишаються незмінними і зберігають свої початкові відтінки.",
                            DiscountPercent = 0f,
                            Name = "Плямовивідник Ariel Diamond Bright для білого та кольорового 750 мл",
                            PhotoPath = "/product3",
                            Price = 157.25f,
                            ProducerId = "ariel01",
                            StatusId = "avaliable",
                            WeightInKilogram = 0.75f
                        },
                        new
                        {
                            Id = "a561e284-f6dd-4c2a-aa06-df2bf4d02102",
                            Article = "SV536988",
                            CategoryId = "category1",
                            Description = "Пральний порошок Ariel Аква-Пудра Дотик свіжості Lenor автомат 5,4 кг",
                            DiscountPercent = 15f,
                            Name = "Пральний порошок Ariel Аква-Пудра Дотик свіжості Lenor автомат 5,4 кг",
                            PhotoPath = "/product4",
                            Price = 585f,
                            ProducerId = "ariel01",
                            StatusId = "avaliable",
                            WeightInKilogram = 5.45f
                        },
                        new
                        {
                            Id = "4249c221-181c-4614-bd93-806a05278082",
                            Article = "HP921552",
                            CategoryId = "category1",
                            Description = "Універсальні капсули для прання Ariel All-in-1 забезпечують високу ефективність прання та протидіють широкому спектру плям. Капсули складаються з окремих камери, які вивільняють інгредієнти лише тоді, коли вони потрібні під час процесу прання. Інноваційна оболонка капсули Ariel All-in-1 повністю розчиняється при контакті з водою і є біологічно розкладною. \r\n\r\nНайкращий рідкий миючий засіб від Ariel з оптимальним дозуванням : 1 капсула на 1 цикл прання. Помістіть капсулу в барабан, а потім одяг зверху, щоб ефективно використовувати продукт.",
                            DiscountPercent = 0f,
                            Name = "Капсули для прання Ariel All-in-1 універсальні 42 шт",
                            PhotoPath = "/product5",
                            Price = 335f,
                            ProducerId = "ariel01",
                            StatusId = "notAvaliable",
                            WeightInKilogram = 5.45f
                        },
                        new
                        {
                            Id = "ec5e7ea6-be19-4c9b-8b49-5c82ba510734",
                            Article = "DM178949",
                            CategoryId = "category3",
                            Description = "Гель для чищення труб W5 1 л\r\n\r\nГель для очищення каналізаційних труб W5 ефективно усуває навіть стійкі засмічення, викликані волоссям, залишками харчових відходів, жиром або милом, і підходить для всіх поширених типів труб. Потужна високоефективна формула також усуває неприємні запахи для гігієнічної чистоти.",
                            DiscountPercent = 0f,
                            Name = "Гель для чищення труб W5 1 л",
                            PhotoPath = "/product6",
                            Price = 76f,
                            ProducerId = "W502",
                            StatusId = "avaliable",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "db7e9e15-3fcb-451b-ae37-2f53b78104f2",
                            Article = "DM018889",
                            CategoryId = "category3",
                            Description = "Гель антибактеріальний для очищення туалету \"ЕКО\" W5 Toilet Cleaner справляється із різними забрудненнями, наділений легкою антибактеріальною дією. Чистяча рідина не завдасть шкоди шкірі людини. Ваш унітаз просто сяятиме чистотою, як новий. На ньому не залишиться жодних розводів, а вашій туалетній кімнаті забезпечена гігієнічна чистота та свіжість. Ефективний і високоякісний засіб для чищення унітазів, ретельне миття забезпечує спеціальними компонентами, що містяться в засобі. Форма пляшки досить зручна для того, щоб наносити засіб навіть у «затишні куточки», такі як обідок унітазу. Засіб має приємний лимонний запах.",
                            DiscountPercent = 20f,
                            Name = "Гель для чищення унітазу W5 Eco Lemon екологічний 1 л",
                            PhotoPath = "/product7",
                            Price = 59f,
                            ProducerId = "W502",
                            StatusId = "runOut",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "e02a1813-4cf3-4c96-8d85-8c2403a20516",
                            Article = "DM168423",
                            CategoryId = "category3",
                            Description = "W5 спрей для чищення ванної з ароматом океану. Засіб призначений для миття плитки, стиків та сантехніки. Корисний скрізь, де є потреба гігієнічної чистоти. Без особливих труднощів позбавить від вапняного нальоту та грибка у ванній кімнаті. Завдяки W5 очищені поверхні надовго збережуть свій первісний вигляд і стануть чистими та блискучими. Виріб має зручний розпилювач, що створює активну піну. У складі лише натуральні компоненти рослинного та мінерального походження.",
                            DiscountPercent = 0f,
                            Name = "Засіб для миття ванни W5 Kraft & Glanz Ocean спрей 1 л",
                            PhotoPath = "/product8",
                            Price = 80f,
                            ProducerId = "W502",
                            StatusId = "avaliable",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "15e741f5-6206-4063-828a-fb139c98c34c",
                            Article = "GT018896",
                            CategoryId = "category3",
                            Description = "Універсальна рідина для прибирання W5 Eco ідеально підходить для щоденного догляду за різними типами поверхонь, що миються, включаючи підлогу, стіни і плитку. Засіб містить поверхнево-активні речовини рослинного походження. Ефективне прибирання із турботою про навколишнє середовище!\r\n\r\nЕкологічний миючий засіб W5 Eco призначений для всіх видів покриттів, а саме кахель, керамограніт, ламінат, пластик, вініл, лінолеум та ін.\r\n\r\nW5 Eco забезпечує ідеальну чистоту всіх поверхонь без тертя та надмірних зусиль та залишає легкий аромат свіжості.",
                            DiscountPercent = 0f,
                            Name = "Засіб для прибирання W5 Eco універсальний екологічний 1,25 л",
                            PhotoPath = "/product8",
                            Price = 80f,
                            ProducerId = "W502",
                            StatusId = "avaliable",
                            WeightInKilogram = 1.25f
                        },
                        new
                        {
                            Id = "ef85206f-a6fd-4420-94b0-35fe2578e77a",
                            Article = "EU052476",
                            CategoryId = "category4",
                            Description = "БОНУС⁺ Чарівна губка для миття посуду – це ключ до чистоти кожної кухні та ванної кімнати. Зробіть прибирання незабутнім!\r\n\r\nКраса та додаткова ефективність — ці дві речі характеризують губку для миття посуду BONUS⁺ без подряпин, яка є незамінним аксесуаром для будь-якого стильного будинку.\r\n\r\nАбразивний шар без подряпин з веселим малюнком м'яко очищає забруднення. Як? Секрет криється у якісній губчастій піні та абразивному шарі без подряпин. Незалежно від того, чи це плями фарби на плитці чи на вікнах після фарбування, для губки BONUS + Magical немає неможливої місії.",
                            DiscountPercent = 0f,
                            Name = "Губка BONUS Magical easy grip sponge scourer для миття посуду 2 шт",
                            PhotoPath = "/product9",
                            Price = 27.95f,
                            ProducerId = "Bonus03",
                            StatusId = "avaliable",
                            WeightInKilogram = 0.1f
                        },
                        new
                        {
                            Id = "eecbff61-813f-442d-862e-7caaa2094c98",
                            Article = "EU301491",
                            CategoryId = "category3",
                            Description = "BONUS CottonMOP забезпечує блискучу чистоту підлоги!\r\n\r\nУ кожному помешканні є критичні точки для чистоти, в більшості випадків це не що інше, як підлога. Тому дуже важливо використовувати зручний та надійний інструмент, щоб мити підлогу. І це саме про BONUS CottonMOP. Найкраще використовувати його універсально для всіх видів підлогових поверхонь, на кухні, у ванній, вітальні або навіть використовувати на відкритому повітрі, на терасі або перед вхідними дверима.",
                            DiscountPercent = 11f,
                            Name = "Моп BONUS Cotton Mop Насадка для швабри 30*9*6 см (бавовна) (L)",
                            PhotoPath = "/product10",
                            Price = 47.04f,
                            ProducerId = "Bonus03",
                            StatusId = "avaliable",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "db634885-e457-42bb-b98c-6a6a07006b60",
                            Article = "EU052629",
                            CategoryId = "category3",
                            Description = "BONUS + MicroMOP – це найефективніша абсорбуюча насадка для гладких поверхонь підлоги.\r\n\r\nОднією з найбільших проблем під час миття підлоги є складність по-справжньому зібрати бруд. Недостатньо просто протерти підлогу, тільки справді якісна насадка для швабри може дійсно зібрати, а не розтерти бруд по поверхні. MicroMOP може зробити це без зусиль, оскільки вона чудово поглинає вологу і стає достатньо масивною у вологому стані, тому не потрібно тиснути на підлогу під час прибирання. Одним рухом можна досягти дивовижної чистоти, а поверхня залишається майже сухою.",
                            DiscountPercent = 0f,
                            Name = "Моп BONUS MicroMop Насадка для швабри мікрофібра 30*11*8 см (колір зелений+фіолет)",
                            PhotoPath = "/product11",
                            Price = 142f,
                            ProducerId = "Bonus03",
                            StatusId = "notAvaliable",
                            WeightInKilogram = 1f
                        },
                        new
                        {
                            Id = "37c2f224-5515-47e8-a2c9-e7744705bbf9",
                            Article = "EU303471",
                            CategoryId = "category4",
                            Description = "Набір для кухні BONUS Kitchen Smart Pack",
                            DiscountPercent = 11f,
                            Name = "Набір для кухні BONUS Kitchen Smart Pack",
                            PhotoPath = "/product12",
                            Price = 208f,
                            ProducerId = "Bonus03",
                            StatusId = "avaliable",
                            WeightInKilogram = 0.1f
                        },
                        new
                        {
                            Id = "8448f1d5-962b-41ea-8950-0dece21551af",
                            Article = "MB116546",
                            CategoryId = "category3",
                            Description = "Ефективний засіб для унітазів і пісуарів Domestos professional Original Pro Formula підходить для використання на фарфорових і глянсових поверхнях. Він входить у лінійку професійних сильнодіючих продуктів Pro Formula, розроблених для прибирання великих об'єктах: готелі, ресторани, навчальні заклади, торгові площі. Такий засіб з легкістю подолає побутові забруднення. Засіб видаляє сильні забруднення і вапняний наліт, відкладення, іржу, сечовий камінь і мильні розводи. Даний засіб є ефективним проти нальоту та інших забруднень, властивих сантехніці.",
                            DiscountPercent = 0f,
                            Name = "Гель для чищення унітазу Domestos professional Original Pro Formula 750 мл",
                            PhotoPath = "/product13",
                            Price = 144f,
                            ProducerId = "Domestos04",
                            StatusId = "notAvaliable",
                            WeightInKilogram = 0.75f
                        },
                        new
                        {
                            Id = "12931cb8-d606-47e1-8a05-7898c5663e97",
                            Article = "MY635729",
                            CategoryId = "category3",
                            Description = "Гель для туалету Domestos WC Gel — це надзвичайно густий засіб для чищення унітазів для економічного використання та ідеальної чистоти та гігієни. \r\n\r\nУнікальна дозувальна насадка Domestos дозволяє рівномірно розподіляє гель навіть у важкодоступних місцях. Він видаляє стійкі забруднення та відкладення вапняного нальоту, іржі та утворює захисний щит від утворення нового вапняного нальоту. \r\n\r\nЗасіб для чищення Domestos WC Gel наповнює ароматом океану і гарантує інтенсивну свіжість. Забезпечує гігієнічну та довготривалу чистоту та надає унітазу блиску та білизни.",
                            DiscountPercent = 8f,
                            Name = "Гель для чищення унітазу Domestos Zero WC Gel Blue 750 мл",
                            PhotoPath = "/product14",
                            Price = 104f,
                            ProducerId = "Domestos04",
                            StatusId = "avaliable",
                            WeightInKilogram = 0.75f
                        },
                        new
                        {
                            Id = "c0ce1483-f2ac-496e-9d87-f8481eb25520",
                            Article = "MB813759",
                            CategoryId = "category3",
                            Description = "Засіб для чищення Domestos Citros Fresh Pro Formula \"Лимонна свіжість\" є універсальним. Він запобігає повторній появі грибка, надає дезінфікуючу дію, видаляє всі відомі мікроби. Достатньо невелику кількість засобу нанести на ганчірку або губку, щоб повністю продезінфікувати та очистити ванну кімнату та туалет. Чудово справляється із вапняним нальотом, видаляє плями будь-якого походження. Залишає після себе свіжий аромат лимона.",
                            DiscountPercent = 0f,
                            Name = "Гель для чищення унітазу Domestos professional Citrus Fresh Pro Formula 5 л",
                            PhotoPath = "/product15",
                            Price = 447f,
                            ProducerId = "Domestos04",
                            StatusId = "notAvaliable",
                            WeightInKilogram = 5f
                        },
                        new
                        {
                            Id = "bf8d5715-a11a-4e57-8e80-e2e309e15051",
                            Article = "MB813742",
                            CategoryId = "category3",
                            Description = "Універсальний миючий засіб Domestos professional Pine Fresh Pro Formula з ароматом Хвої з дезінфікуючим ефектом для миття підлоги, туалету, раковин, ванн, стоків, підлоги та приладів у медичних закладах, санітарних приміщеннях, будинках у ресторанах та готелях тепер простіше та ефективніше. Завдяки густій консистенції засіб довше прилипає до поверхні, що очищається і більш ефективно видаляє забруднення. Відмінно підходить для місць, де важлива чистота та стерильність, і де щодня люди або готуються їжа.",
                            DiscountPercent = 0f,
                            Name = "Гель для чищення унітазу Domestos professional Pine Fresh Pro Formula 5 л",
                            PhotoPath = "/product16",
                            Price = 403f,
                            ProducerId = "Domestos04",
                            StatusId = "notAvaliable",
                            WeightInKilogram = 5f
                        },
                        new
                        {
                            Id = "50ba34c9-2888-47bb-ac72-948a3e0c7f5d",
                            Article = "DM485915",
                            CategoryId = "category4",
                            Description = "Таблетки Denkmit проти вапняного нальоту мают силу подвійної дії: вони забезпечують надійний захист від вапняного нальоту як для машини, так і для білизни, а завдяки формулі захисту від бруду підтримують машину в чистоті. Регулярне використання засобу продовжить термін служби вашої пральної машини. Крім того, ви заощаджуєте миючий засіб, оскільки при використанні таблеток проти вапняного нальоту вам потрібно дозувати миючий засіб лише для діапазону жорсткості м’якої води – незалежно від того, наскільки жорстка ваша вода. ",
                            DiscountPercent = 0f,
                            Name = "Засіб від накипу Denkmit у таблетках 60 шт",
                            PhotoPath = "/product17",
                            Price = 316f,
                            ProducerId = "Denkmit05",
                            StatusId = "runOut",
                            WeightInKilogram = 2.5f
                        },
                        new
                        {
                            Id = "f2204903-9189-49cf-af0e-22618166a19f",
                            Article = "DM289619",
                            CategoryId = "category4",
                            Description = "Засіб Denkmit Супердія призначений для ефективного видалення жиру і нагару з кухонних поверхонь, плит, духовок, мікрохвильових печей та інших обладнаннях.",
                            DiscountPercent = 12f,
                            Name = "Засіб для видалення жиру і нагару Denkmit Супердія 750 мл",
                            PhotoPath = "/product18",
                            Price = 720f,
                            ProducerId = "Denkmit05",
                            StatusId = "avaliable",
                            WeightInKilogram = 0.75f
                        },
                        new
                        {
                            Id = "41cbc7bf-45d2-401c-b7a2-615130a3dbe6",
                            Article = "DM294647",
                            CategoryId = "category3",
                            Description = "Засіб для очищення ламінату та пробкових підлог від Denkmit має формулу швидкого висихання, а також спеціальний захист стиків від вологи та здуття. Підходить для ламінату, пробки, вінілу та лінолеуму.\r\n\r\n*Упаковка містить не менше 70% переробленого вмісту.",
                            DiscountPercent = 0f,
                            Name = "Засіб для миття ламінату Denkmit 1л",
                            PhotoPath = "/product19",
                            Price = 66f,
                            ProducerId = "Denkmit05",
                            StatusId = "avaliable",
                            WeightInKilogram = 1f
                        });
                });

            modelBuilder.Entity("DiplomeProject.DB.Models.ProductStatus", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductStatuses");

                    b.HasData(
                        new
                        {
                            Id = "avaliable",
                            StatusCode = 0,
                            StatusName = "В наявності"
                        },
                        new
                        {
                            Id = "runOut",
                            StatusCode = 1,
                            StatusName = "Закінчується"
                        },
                        new
                        {
                            Id = "notAvaliable",
                            StatusCode = 2,
                            StatusName = "Немає в наявності"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b7b0b1b7-34ef-4534-b92c-d1599dffc86f",
                            ConcurrencyStamp = "4c0afc8b-b2fd-4907-bc18-ba6c682fbd8a",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiplomeProject.DB.Models.Product", b =>
                {
                    b.HasOne("DiplomeProject.DB.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomeProject.DB.Models.Producer", "Producer")
                        .WithMany()
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomeProject.DB.Models.ProductStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Producer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DiplomeProject.DB.IdentityModels.DbUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DiplomeProject.DB.IdentityModels.DbUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomeProject.DB.IdentityModels.DbUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DiplomeProject.DB.IdentityModels.DbUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
